# Generated by Django 5.2.9 on 2025-12-12 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0003_create_change_status_choices'),
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='resources',
        ),
        migrations.AddField(
            model_name='allocation',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.resource'),
        ),
        migrations.AddField(
            model_name='historicalallocation',
            name='resource',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resource.resource'),
        ),
    ]
