# Generated by Django 5.2.9 on 2025-12-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0004_remove_allocation_resources_allocation_resource_and_more'),
        ('project', '0001_initial'),
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.UniqueConstraint(fields=('project', 'resource'), name='uniq_allocation_project_resource'),
        ),
    ]
