# Generated by Django 5.2.9 on 2025-12-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0005_allocation_uniq_allocation_project_resource'),
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='resources',
            field=models.ManyToManyField(related_name='allocations_m2m', to='resource.resource'),
        ),
    ]
