# Generated by Django 5.2.18 on 2026-10-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='nyu_cayuse_id',
            field=models.CharField(default='', max_length=255, verbose_name='NYU Cayuse ID'),
        ),
        migrations.AddField(
            model_name='historicalgrant',
            name='nyu_cayuse_id',
            field=models.CharField(default='', max_length=255, verbose_name='NYU Cayuse ID'),
        ),
    ]
